#!/bin/bash

echo 'Hello world';
ls;
zmienna='to jest zmienna tekstowa';
echo $zmienna;
a=7;
b=3;
# matematyka nie działa
echo $a + $b = $(($a + $b));
echo $a / $b = $(($a / $b));

wyjscie_ls=`ls`;
echo $wyjscie_ls;

echo $@;
echo $0;
echo $1;
echo $2;

#if [ 0 > 2 ]; then
if [ 0 -gt 2 ]; then
#	-eq -- ==
#	-le -- less or equal
#	-ge -- greater or equal
#	-lt -- less than
#	-gt -- greater than
	echo '0 jest większe';
elif [ 0 -lt 0 ]; then
	echo '0 jest mniejsze';
else
	echo 'wszystko inne';
fi

i=1;
while [ $i -le 10 ]; do
	echo $i;
	((i += 1));
done;

for i in {1..10}; do
	echo $i;
done;

for i in 'kot' 'pies' 'mleko'; do
	echo $i;
done;
